version: '3.8'

services:
  api:
    image: amltd-api-flask
    ports:
      - 5090:5080
    env_file:
      - .env.prod
    depends_on:
      - db-postgres

  db-postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-admindev007}'
      POSTGRES_DB: '${POSTGRES_DB:-amltd_task_db}'
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: